- path: "a0-ostashkov-volgoverkhovye.gpx"
    color: "fuchsia"
    title: "–û—Å—Ç–∞—à–∫–æ–≤ - –í–æ–ª–≥–æ–≤–µ—Ä—Ö–æ–≤—å–µ - –û—Å—Ç–∞—à–∫–æ–≤"
    width: widthCycleRoute
    links:
      - "https://volgagrandtour.github.io/#a0"
  - path: "a1-ostashkov-torzhok.gpx"
    color: green1
    title: "–û—Å—Ç–∞—à–∫–æ–≤ - –¢–æ—Ä–∂–æ–∫"
    width: widthCycleRoute
    links:
      - "https://volgagrandtour.github.io/#a1"
  - path: "a2-torzhok-tver.gpx"
    color: green2
    title: "–¢–æ—Ä–∂–æ–∫ - –¢–≤–µ—Ä—å"
    width: widthCycleRoute
    links:
      - "https://volgagrandtour.github.io/#a2"
  - path: "a3-tver-toporok.gpx"
    color: green1
    title: "–¢–≤–µ—Ä—å - –ö–æ–Ω–∞–∫–æ–≤–æ"
    width: widthCycleRoute
    links:
      - "https://volgagrandtour.github.io/#a3"
  - path: "a3b-tver-toporok-gravel-short-part-of-a3.gpx"
    color: green2
    title: "–ì—Ä–∞–≤–∏–π–Ω—ã–π –≤–∞—Ä–∏–∞–Ω—Ç –ø–æ –±–µ—Ä–µ–≥—É –¢–≤–µ—Ä—å - –ö–æ–Ω–∞–∫–æ–≤–æ"
    width: widthCycleRoute
    links:
      - "https://volgagrandtour.github.io/#a3b"
  - path: "river-1-toporok-preprava-river.gpx"
    color: "DeepSkyBlue"
    title: "üö¢ –ü–µ—Ä–µ–ø—Ä–∞–≤–∞ –¢–æ–ø–æ—Ä–æ–∫ - –ó–µ–ª–µ–Ω—ã–π –ë–æ—Ä"
    width: widthCycleRoute
    links:
      - "https://volgagrandtour.github.io/#river-1"
  - path: "b1-konakovo-dubna.gpx"
    color: green2
    title: "–ö–æ–Ω–∞–∫–æ–≤–æ - –î—É–±–Ω–∞"
    width: widthCycleRoute
    links:
      - "https://volgagrandtour.github.io/#b1"
  - path: "river-2-kanal-moscow-dubna.gpx"
    color: "DeepSkyBlue"
    title: "üö¢ –ü–µ—Ä–µ–ø—Ä–∞–≤–∞ —á–µ—Ä–µ–∑ –∫–∞–Ω–∞–ª –∏–º. –ú–æ—Å–∫–≤—ã"
    width: widthCycleRoute
    links:
      - "https://volgagrandtour.github.io/#river-2"
  - path: "b2-dubna-kimry.gpx"
    color: green1
    title: "–î—É–±–Ω–∞ - –ö–∏–º—Ä—ã (–°–∞–≤–µ–ª–æ–≤–æ)"
    width: widthCycleRoute
    links:
      - "https://volgagrandtour.github.io/#b2"
  - path: "b3-kimry-kalyazin.gpx"
    color: "yellow"
    title: "–ö–∏–º—Ä—ã (–°–∞–≤–µ–ª–æ–≤–æ) - –ö–∞–ª—è–∑–∏–Ω"
    width: widthCycleRoute
    links:
      - "https://volgagrandtour.github.io/#b3"
  - path: "c1-kalyazin-uglich.gpx"
    color: green1
    title: "–ö–∞–ª—è–∑–∏–Ω - –£–≥–ª–∏—á"
    width: widthCycleRoute
    links:
      - "https://volgagrandtour.github.io/#c1"
  - path: "c2-uglich-myshkin.gpx"
    color: green2
    title: "–£–≥–ª–∏—á - –ú—ã—à–∫–∏–Ω"
    width: widthCycleRoute
    links:
      - "https://volgagrandtour.github.io/#c2"
  - path: "rw1-bologoe-ostachkov.gpx"
    title: "üöÇ –ë–æ–ª–æ–≥–æ–µ - –û—Å—Ç–∞—à–∫–æ–≤"
    color: railwayColor
    width: widthRailway
    links:
      - "https://volgagrandtour.github.io/#rw1"
  - path: "rw1a-ostashkov-kuvchinovo.gpx"
    title: "üöÇ –û—Å—Ç–∞—à–∫–æ–≤ - –ö—É–≤—à–∏–Ω–æ–≤–æ"
    color: railwayColor
    width: widthRailway
    links:
      - "https://volgagrandtour.github.io/#rw1a"
  - path: "rw2-torzhok-tver.gpx"
    title: "üöÇ –¢–æ—Ä–∂–æ–∫ - –¢–≤–µ—Ä—å"
    color: railwayColor
    width: widthRailway
    links:
      - "https://volgagrandtour.github.io/#rw2"
